import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav style={{background: 'blue' , padding: '20px' , textAlign: "center" }}>
          <Link  style={{ padding: "20px"}} href='/'>
            Home
          </Link>
          <Link style={{ padding: "20px"}} href='/posts'>
            posts
          </Link>
          <Link style={{ padding: "20px"}} href='/article'>
          article
          </Link>
        </nav>
        {children}</body>
    </html>
  )
}
